apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-vvec
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-vvec
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-vvec
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-vvec
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-vvec
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ybox-tenant/rhtap-demo-app/hacbs-test-project-vvec@sha256:edafe7360a06f9bc9e896b59a2ab4f11869196daf75d0d43bd2a5874b980453b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
